build: false

platform:
  - x64

environment:
  matrix:
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda3-x64

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - where conda
  - dir %MINICONDA%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -c conda-forge -n test-environment python=%PYTHON_VERSION% numpy scipy pytest pandas scikit-learn librosa keras tensorflow mingw ffmpeg"
  - activate test-environment
  - echo %PATH%
  - where gcc
  - pip install pytest-cov
  - pip install -r requirements.txt
  - pip install ./ -v

test_script:
  - pytest -v


